package com.example.ui.localization

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val displayName: String, val isRtl: Boolean) {
    ARABIC("ar", "العربية (RTL)", true),
    ENGLISH("en", "English (LTR)", false)
}

data class AppStrings(
    // Navigation
    val navDashboard: String,
    val navStats: String,
    val navAiCoach: String,
    val navAddHabit: String,
    val navSettings: String,

    // Dashboard
    val greeting: String,
    val todayHabits: String,
    val habitsCountSuffix: String,
    val todayProgress: String,
    val progressDetailFormat: (Int, Int) -> String,
    val noHabitsYet: String,
    val longestStreakFormat: (Int) -> String,
    val allCompletedCongrats: String,
    val filterAllFormat: (Int) -> String,
    val filterPendingFormat: (Int) -> String,
    val filterCompletedFormat: (Int) -> String,
    val addHabitFab: String,
    val deleteHabitTitle: String,
    val deleteHabitMessage: (String) -> String,
    val confirmDelete: String,
    val cancel: String,
    val emptyAllTitle: String,
    val emptyAllDesc: String,
    val emptyCompletedTitle: String,
    val emptyCompletedDesc: String,
    val emptyPendingTitle: String,
    val emptyPendingDesc: String,
    val addFirstHabitButton: String,

    // Add Habit Screen
    val addHabitTitle: String,
    val habitNameLabel: String,
    val habitNamePlaceholder: String,
    val habitNameError: String,
    val frequencyLabel: String,
    val freqDaily: String,
    val freqWeekdays: String,
    val freqWeekends: String,
    val freqWeekly3: String,
    val freqCustom: String,
    val selectDaysTitle: String,
    val timeOfDayLabel: String,
    val timeAnytime: String,
    val timeMorning: String,
    val timeAfternoon: String,
    val timeEvening: String,
    val habitIconLabel: String,
    val habitColorLabel: String,
    val notesLabel: String,
    val notesPlaceholder: String,
    val saveHabitButton: String,
    val backButtonDesc: String,

    // Settings Screen
    val settingsTitle: String,
    val statsTitle: String,
    val statsTotalHabits: String,
    val statsCompletedToday: String,
    val statsLongestStreak: String,
    val daysSuffix: String,
    val appearanceSection: String,
    val themePaletteLabel: String,
    val lightingModeLabel: String,
    val darkModeLabel: String,
    val lightModeLabel: String,
    val cardDensityLabel: String,
    val densityComfortable: String,
    val densityCompact: String,
    val fontScaleLabel: String,
    val livePreviewLabel: String,
    val sampleHabitName: String,
    val sampleHabitDetail: String,
    val resetThemeButton: String,

    // Language & RTL
    val languageSection: String,
    val appLanguageLabel: String,
    val layoutDirectionLabel: String,
    val layoutDirectionValue: String,
    val switchLanguageDialogTitle: String,

    // Forgiving Streak & Momentum
    val forgivingStreakSection: String,
    val forgivingStreakDesc: String,
    val streakFrozenBadge: String,
    val momentumLabel: String,
    val momentumExplanation: String,

    // Habit Stacking & Health Integration
    val habitStackingTitle: String,
    val habitStackingDesc: String,
    val anchorHabitLabel: String,
    val selectAnchorHabitPlaceholder: String,
    val noAnchorOption: String,
    val stackCueLabel: String,
    val stackCuePlaceholder: String,
    val healthSyncTitle: String,
    val healthSyncDesc: String,
    val targetStepsLabel: String,
    val stepsCardTitle: String,
    val stepsCardSub: String,
    val refreshSensor: String,
    val addTestSteps: String,

    // Vacation Mode
    val vacationModeLabel: String,
    val vacationModeDesc: String,
    val vacationActiveBanner: String,

    // Reminders
    val remindersSection: String,
    val dailyReminderLabel: String,
    val dailyReminderDesc: String,
    val reminderTimeLabel: String,
    val editButton: String,
    val testReminderBtn: String,
    val testReminderDesc: String,
    val pendingReminderExplanation: String,

    // Data Management
    val dataManagementSection: String,
    val resetTodayLabel: String,
    val resetTodayDesc: String,
    val resetTodayConfirmTitle: String,
    val resetTodayConfirmMessage: String,
    val resetTodayConfirmBtn: String,
    val loadSampleHabitsLabel: String,
    val loadSampleHabitsDesc: String,
    val loadBtn: String,
    val clearAllDataLabel: String,
    val clearAllDataDesc: String,
    val clearAllDataConfirmTitle: String,
    val clearAllDataConfirmMessage: String,
    val clearAllDataConfirmBtn: String,

    // About
    val appNameDisplay: String,
    val appVersionInfo: String,
    val appQuote: String,

    // Frequency display helpers
    val freqDailyDisplay: String,
    val freqWeekdaysDisplay: String,
    val freqWeekendsDisplay: String,
    val freqWeekly3Display: String,
    val freqCustomDisplay: String,

    // Days of week short labels
    val daysOfWeekLabels: List<String>
)

val ArabicStrings = AppStrings(
    navDashboard = "عاداتي",
    navStats = "الإحصائيات",
    navAiCoach = "المدرب الذكي",
    navAddHabit = "إضافة عادة",
    navSettings = "الإعدادات",

    greeting = "مرحباً بك!",
    todayHabits = "عادات اليوم",
    habitsCountSuffix = "عادات",
    todayProgress = "إنجاز اليوم",
    progressDetailFormat = { done, total -> "أنجزت $done من أصل $total عادات" },
    noHabitsYet = "لم تضف عادات لليوم بعد",
    longestStreakFormat = { streak -> "أعلى التزام: $streak أيام متتالية" },
    allCompletedCongrats = "رائع! اكتملت جميع العادات ✨",
    filterAllFormat = { count -> "الكل ($count)" },
    filterPendingFormat = { count -> "المتبقية ($count)" },
    filterCompletedFormat = { count -> "المكتملة ($count)" },
    addHabitFab = "إضافة عادة",
    deleteHabitTitle = "حذف العادة",
    deleteHabitMessage = { name -> "هل أنت متأكد من رغبتك في حذف عادة \"$name\"؟ سيتم مسح سجل إنجازاتها نهائياً." },
    confirmDelete = "نعم، حذف",
    cancel = "إلغاء",
    emptyAllTitle = "لا توجد عادات مضافة بعد",
    emptyAllDesc = "ابدأ رحلة بناء عاداتك اليومية واستمر في التطوير المستمر",
    emptyCompletedTitle = "لم تكتمل أي عادة حتى الآن",
    emptyCompletedDesc = "اضغط على مربع العادة في القائمة عند إنجازها",
    emptyPendingTitle = "أحسنت! لا توجد عادات متبقية لليوم",
    emptyPendingDesc = "لقد أنجزت كل ما خططت له لهذا اليوم بامتياز!",
    addFirstHabitButton = "أضف عادتك الأولى",

    addHabitTitle = "إضافة عادة جديدة",
    habitNameLabel = "اسم العادة *",
    habitNamePlaceholder = "مثال: قراءة 20 دقيقة، شرب الماء، مشي...",
    habitNameError = "يرجى إدخال اسم العادة أولاً",
    frequencyLabel = "تكرار العادة (التكرار) *",
    freqDaily = "يومي",
    freqWeekdays = "أيام العمل",
    freqWeekends = "عطلة الأسبوع",
    freqWeekly3 = "3 مرات أسبوعياً",
    freqCustom = "أيام محددة",
    selectDaysTitle = "حدد أيام التكرار:",
    timeOfDayLabel = "وقت الممارسة المفضل",
    timeAnytime = "أي وقت",
    timeMorning = "صباحاً",
    timeAfternoon = "ظهراً",
    timeEvening = "مساءً",
    habitIconLabel = "أيقونة العادة *",
    habitColorLabel = "لون تمييز العادة",
    notesLabel = "ملاحظة أو دافع ملهم (اختياري)",
    notesPlaceholder = "اكتب كلمة تشجيعية أو تفاصيل تذكرك بأهمية هذه العادة...",
    saveHabitButton = "حفظ العادة",
    backButtonDesc = "الرجوع للرئيسية",

    settingsTitle = "الإعدادات والمظهر",
    statsTitle = "إحصائيات الإنجاز",
    statsTotalHabits = "إجمالي العادات",
    statsCompletedToday = "المكتملة اليوم",
    statsLongestStreak = "أعلى التزام",
    daysSuffix = "أيام",
    appearanceSection = "تخصيص الواجهة والمظهر",
    themePaletteLabel = "سمة الألوان (Color Palette)",
    lightingModeLabel = "نمط الإضاءة",
    darkModeLabel = "الوضع الداكن",
    lightModeLabel = "الوضع الفاتح",
    cardDensityLabel = "كثافة عرض بطاقات العادات",
    densityComfortable = "مريح (كامل)",
    densityCompact = "مدمج (سريع)",
    fontScaleLabel = "حجم الخط والنصوص",
    livePreviewLabel = "معاينة حية للمظهر الحالي",
    sampleHabitName = "قراءة 20 دقيقة",
    sampleHabitDetail = "يومياً • مساءً",
    resetThemeButton = "استعادة المظهر الافتراضي (الأرجواني الملكي الداكن)",

    languageSection = "اللغة والاتجاه",
    appLanguageLabel = "لغة الواجهة (Language)",
    layoutDirectionLabel = "محاذاة النص والاتجاه",
    layoutDirectionValue = "من اليمين إلى اليسار (RTL)",
    switchLanguageDialogTitle = "اختر لغة التطبيق / Select Language",

    forgivingStreakSection = "نظام السلسلة المتسامحة وحماية الزخم",
    forgivingStreakDesc = "حماية سلسلتك من التصفير وتجميدها تلقائياً (Streak Freeze) عند تفويت يوم واحد",
    streakFrozenBadge = "مجمدة ❄️",
    momentumLabel = "زخم",
    momentumExplanation = "بدلاً من العقاب القاسي وتصفير إنجازك بالكامل عند نسيان يوم واحد، يحافظ نظام السلسلة المتسامحة والزخم (Momentum) على تقدمك ويمنحك فرصة فورية للتعويض والاستمرار دون إحباط.",

    habitStackingTitle = "تجميع العادات (Habit Stacking)",
    habitStackingDesc = "اربط هذه العادة بروتين قائم لديك لضمان الالتزام بها (استراتيجية العادات الذرية)",
    anchorHabitLabel = "العادة المحفزة (بعد ماذا؟)",
    selectAnchorHabitPlaceholder = "اختر عادة قائمة لربطها بها...",
    noAnchorOption = "بدون ربط (عادة مستقلة)",
    stackCueLabel = "صيغة الرابط / المحفز",
    stackCuePlaceholder = "مثال: بعد شرب قهوة الصباح مباشرة ☕",
    healthSyncTitle = "التكامل الصحي وتتبع الخطوات",
    healthSyncDesc = "إنجاز العادة تلقائياً عند تحقيق عدد الخطوات المطلوب لليوم من حساس الهاتف",
    targetStepsLabel = "الهدف المطلوب (عدد الخطوات)",
    stepsCardTitle = "تتبع الخطوات والصحة اليومية",
    stepsCardSub = "إنجاز تلقائي لعادات المشي والصحة",
    refreshSensor = "تحديث",
    addTestSteps = "+1,000 خطوة",

    vacationModeLabel = "وضع الإجازة والمرض (Vacation Mode)",
    vacationModeDesc = "إيقاف احتساب العادات مؤقتاً وحماية سلاسلك وزخمك بنسبة 100% أثناء السفر أو المرض",
    vacationActiveBanner = "🏖️ وضع الإجازة مفعّل: استمتع برحلتك وراحتك دون قلق، سلاسلك وإحصائياتك محمية بالكامل.",

    remindersSection = "التذكيرات والإشعارات",
    dailyReminderLabel = "تذكير مجدول بالعادات",
    dailyReminderDesc = "تنبيه ذكي لتذكيرك بالعادات التي لم تكتمل بعد خلال اليوم",
    reminderTimeLabel = "وقت التذكير اليومي",
    editButton = "تعديل",
    testReminderBtn = "إرسال إشعار تجريبي فوري",
    testReminderDesc = "اختبر ظهور الإشعار مع قائمة عادات اليوم المتبقية",
    pendingReminderExplanation = "يرسل التطبيق تنبيهاً ذكياً في الوقت المحدد فقط إذا كانت لديك عادات متبقية لم تنجزها بعد.",

    dataManagementSection = "إدارة البيانات والتهيئة",
    resetTodayLabel = "تصفير إنجاز اليوم فقط",
    resetTodayDesc = "إلغاء تحديد جميع العادات المكتملة لليوم للبدء من جديد",
    resetTodayConfirmTitle = "تأكيد تصفير إنجاز اليوم",
    resetTodayConfirmMessage = "هل تود إعادة تعيين حالة عادات اليوم وإلغاء اكتمالها؟",
    resetTodayConfirmBtn = "تصفير اليوم",
    loadSampleHabitsLabel = "تحميل عادات تجريبية غنية",
    loadSampleHabitsDesc = "إضافة 5 عادات نموذجية (قراءة، ماء، رياضة، تأمل، أذكار) مع سجل إنجاز لأسبوعين",
    loadBtn = "تحميل العادات",
    clearAllDataLabel = "مسح جميع العادات والبيانات",
    clearAllDataDesc = "حذف كافة العادات وسجلات الإنجاز نهائياً وإعادة التطبيق لحالته الأولى",
    clearAllDataConfirmTitle = "تأكيد المسح الشامل",
    clearAllDataConfirmMessage = "تحذير: سيتم حذف جميع العادات وسجلات الإنجاز السابقة بشكل نهائي. هل تود المتابعة؟",
    clearAllDataConfirmBtn = "حذف الكل",

    appNameDisplay = "تطبيق عاداتي",
    appVersionInfo = "الإصدار 1.2.0 • صُمم لمساعدتك على الاستمرار والنمو",
    appQuote = "«أَحَبُّ الأَعْمَالِ إِلَى اللهِ أَدْوَمُهَا وَإِنْ قَلَّ»",

    freqDailyDisplay = "يومياً",
    freqWeekdaysDisplay = "أيام العمل",
    freqWeekendsDisplay = "عطلة الأسبوع",
    freqWeekly3Display = "3 مرات أسبوعياً",
    freqCustomDisplay = "مخصص",

    daysOfWeekLabels = listOf("الأحد", "الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت")
)

val EnglishStrings = AppStrings(
    navDashboard = "My Habits",
    navStats = "Statistics",
    navAiCoach = "AI Coach",
    navAddHabit = "New Habit",
    navSettings = "Settings",

    greeting = "Welcome Back!",
    todayHabits = "Today's Habits",
    habitsCountSuffix = "habits",
    todayProgress = "Today's Progress",
    progressDetailFormat = { done, total -> "Completed $done of $total habits" },
    noHabitsYet = "No habits scheduled for today",
    longestStreakFormat = { streak -> "Best streak: $streak days in a row" },
    allCompletedCongrats = "Great job! All habits completed ✨",
    filterAllFormat = { count -> "All ($count)" },
    filterPendingFormat = { count -> "Pending ($count)" },
    filterCompletedFormat = { count -> "Done ($count)" },
    addHabitFab = "Add Habit",
    deleteHabitTitle = "Delete Habit",
    deleteHabitMessage = { name -> "Are you sure you want to delete \"$name\"? Its completion history will be removed." },
    confirmDelete = "Delete",
    cancel = "Cancel",
    emptyAllTitle = "No habits added yet",
    emptyAllDesc = "Start building your daily routine and track your personal growth",
    emptyCompletedTitle = "No completed habits yet",
    emptyCompletedDesc = "Tap the check circle when you complete a habit today",
    emptyPendingTitle = "All done for today!",
    emptyPendingDesc = "You have accomplished all your planned habits for today!",
    addFirstHabitButton = "Add Your First Habit",

    addHabitTitle = "Create New Habit",
    habitNameLabel = "Habit Name *",
    habitNamePlaceholder = "e.g., Read 20 mins, Drink water, Gym...",
    habitNameError = "Please enter habit name first",
    frequencyLabel = "Frequency *",
    freqDaily = "Daily",
    freqWeekdays = "Weekdays",
    freqWeekends = "Weekends",
    freqWeekly3 = "3 Times / Week",
    freqCustom = "Custom Days",
    selectDaysTitle = "Select repetition days:",
    timeOfDayLabel = "Preferred Time of Day",
    timeAnytime = "Anytime",
    timeMorning = "Morning",
    timeAfternoon = "Afternoon",
    timeEvening = "Evening",
    habitIconLabel = "Habit Icon *",
    habitColorLabel = "Color Accent",
    notesLabel = "Inspirational Note / Cue (Optional)",
    notesPlaceholder = "Write a motivational sentence or trigger for this habit...",
    saveHabitButton = "Save Habit",
    backButtonDesc = "Back to Dashboard",

    settingsTitle = "Settings & Appearance",
    statsTitle = "Performance Stats",
    statsTotalHabits = "Total Habits",
    statsCompletedToday = "Done Today",
    statsLongestStreak = "Best Streak",
    daysSuffix = "days",
    appearanceSection = "Appearance & Interface",
    themePaletteLabel = "Color Palette",
    lightingModeLabel = "Theme Mode",
    darkModeLabel = "Dark Mode",
    lightModeLabel = "Light Mode",
    cardDensityLabel = "Card Density",
    densityComfortable = "Comfortable (Full)",
    densityCompact = "Compact (Fast)",
    fontScaleLabel = "Font & Text Size",
    livePreviewLabel = "Live Preview",
    sampleHabitName = "Read 20 minutes",
    sampleHabitDetail = "Daily • Evening",
    resetThemeButton = "Reset to Default Theme (Royal Dark Purple)",

    languageSection = "Language & Orientation",
    appLanguageLabel = "App Language",
    layoutDirectionLabel = "Text Direction",
    layoutDirectionValue = "Left to Right (LTR)",
    switchLanguageDialogTitle = "Select Language / اختر لغة التطبيق",

    forgivingStreakSection = "Forgiving Streak & Momentum System",
    forgivingStreakDesc = "Protects your hard-earned streak from resetting to zero with automatic streak freeze",
    streakFrozenBadge = "Frozen ❄️",
    momentumLabel = "Momentum",
    momentumExplanation = "Rather than harsh punishments and zeroing your streak on a single missed day, the Forgiving Streak and Momentum system protects your consistency and keeps your habit momentum strong.",

    habitStackingTitle = "Habit Stacking (Atomic Habits)",
    habitStackingDesc = "Pair this new habit with an established routine to build effortless consistency",
    anchorHabitLabel = "Anchor Habit (After what?)",
    selectAnchorHabitPlaceholder = "Select an existing habit...",
    noAnchorOption = "None (Independent Habit)",
    stackCueLabel = "Stacking Trigger Cue",
    stackCuePlaceholder = "e.g. Right after my morning coffee ☕",
    healthSyncTitle = "Health & Step Counter Sync",
    healthSyncDesc = "Auto-completes this habit once your daily step goal is reached via device sensors",
    targetStepsLabel = "Daily Step Target",
    stepsCardTitle = "Daily Health & Steps",
    stepsCardSub = "Auto-completes walking & health habits",
    refreshSensor = "Refresh",
    addTestSteps = "+1,000 Steps",

    vacationModeLabel = "Vacation & Recovery Mode",
    vacationModeDesc = "Pauses daily habit tracking and protects all streaks while traveling or recovering",
    vacationActiveBanner = "🏖️ Vacation Mode Active: Your streaks and momentum are 100% shielded.",

    remindersSection = "Reminders & Notifications",
    dailyReminderLabel = "Scheduled Habit Reminders",
    dailyReminderDesc = "Smart reminder for habits you haven't completed yet today",
    reminderTimeLabel = "Daily Reminder Time",
    editButton = "Edit",
    testReminderBtn = "Send Test Notification Now",
    testReminderDesc = "Test notification display with your pending habits list",
    pendingReminderExplanation = "The app sends a smart notification at your specified time only if you have remaining pending habits for today.",

    dataManagementSection = "Data Management",
    resetTodayLabel = "Reset Today's Progress Only",
    resetTodayDesc = "Unchecks all habits completed today to start fresh",
    resetTodayConfirmTitle = "Confirm Reset Today",
    resetTodayConfirmMessage = "Do you want to reset all habit completions for today?",
    resetTodayConfirmBtn = "Reset Today",
    loadSampleHabitsLabel = "Load Sample Habits",
    loadSampleHabitsDesc = "Adds 5 diverse sample habits with 2 weeks of completion history",
    loadBtn = "Load Samples",
    clearAllDataLabel = "Clear All Habits & Data",
    clearAllDataDesc = "Permanently deletes all habits and historical records",
    clearAllDataConfirmTitle = "Confirm Full Data Wipe",
    clearAllDataConfirmMessage = "Warning: All habits and history will be permanently deleted. Continue?",
    clearAllDataConfirmBtn = "Clear All",

    appNameDisplay = "My Habits App",
    appVersionInfo = "Version 1.2.0 • Designed for continuous growth",
    appQuote = "\"We are what we repeatedly do. Excellence, then, is not an act, but a habit.\"",

    freqDailyDisplay = "Daily",
    freqWeekdaysDisplay = "Weekdays",
    freqWeekendsDisplay = "Weekends",
    freqWeekly3Display = "3x / Week",
    freqCustomDisplay = "Custom",

    daysOfWeekLabels = listOf("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
)

val LocalAppLanguage = staticCompositionLocalOf { AppLanguage.ARABIC }
val LocalAppStrings = staticCompositionLocalOf { ArabicStrings }

object Strings {
    val current: AppStrings
        @Composable
        @ReadOnlyComposable
        get() = LocalAppStrings.current
}
